# Generated by Django 6.0 on 2026-02-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudySpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('opening_hours', models.CharField(blank=True, max_length=100)),
                ('occupied', models.BooleanField(default=False)),
            ],
        ),
    ]
